### PR TITLE
updated to Biblatex > 3.3

### PR DESCRIPTION
**Pull request by gvdgdo**
Updated name format after Biblatex change to \DeclareNameFormat
parameters.

### CODE REVIEW

**Comment by drewx0r** [comment]
Thanks so much for this. I knew just enough to figure out why the old version didn't work with biblatex > 3.3 but not enough to fix it.

**Comment by gvdgdo** [comment]
Not a problem. I was looking at the issue for other styles.

**Comment by jmclawson** [comment]
Thank you! I've only just updated my installation of biblatex, but I'll happily apply the merge once I try it out.

**Comment by jmclawson** [comment]
Thanks for that, once again. I'll roll it out to CTAN today!

**Pull request merged**
